//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrjPASS.ServiceReference5 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference5.IPartnerIntegrationService")]
    public interface IPartnerIntegrationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartnerIntegrationService/SavePartner_integration", ReplyAction="http://tempuri.org/IPartnerIntegrationService/SavePartner_integrationResponse")]
        string SavePartner_integration(string Partner_integrationXML);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartnerIntegrationService/SavePartner_integration", ReplyAction="http://tempuri.org/IPartnerIntegrationService/SavePartner_integrationResponse")]
        System.Threading.Tasks.Task<string> SavePartner_integrationAsync(string Partner_integrationXML);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPartnerIntegrationServiceChannel : PrjPASS.ServiceReference5.IPartnerIntegrationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PartnerIntegrationServiceClient : System.ServiceModel.ClientBase<PrjPASS.ServiceReference5.IPartnerIntegrationService>, PrjPASS.ServiceReference5.IPartnerIntegrationService {
        
        public PartnerIntegrationServiceClient() {
        }
        
        public PartnerIntegrationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PartnerIntegrationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PartnerIntegrationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PartnerIntegrationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string SavePartner_integration(string Partner_integrationXML) {
            return base.Channel.SavePartner_integration(Partner_integrationXML);
        }
        
        public System.Threading.Tasks.Task<string> SavePartner_integrationAsync(string Partner_integrationXML) {
            return base.Channel.SavePartner_integrationAsync(Partner_integrationXML);
        }
    }
}
