//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrjPASS.MISCReportServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MISCReportServiceReference.IMISCReportService")]
    public interface IMISCReportService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMISCReportService/GetMiniGistDocsDumpReport", ReplyAction="http://tempuri.org/IMISCReportService/GetMiniGistDocsDumpReportResponse")]
        string GetMiniGistDocsDumpReport();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMISCReportService/GetMiniGistDocsDumpReport", ReplyAction="http://tempuri.org/IMISCReportService/GetMiniGistDocsDumpReportResponse")]
        System.Threading.Tasks.Task<string> GetMiniGistDocsDumpReportAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMISCReportServiceChannel : PrjPASS.MISCReportServiceReference.IMISCReportService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MISCReportServiceClient : System.ServiceModel.ClientBase<PrjPASS.MISCReportServiceReference.IMISCReportService>, PrjPASS.MISCReportServiceReference.IMISCReportService {
        
        public MISCReportServiceClient() {
        }
        
        public MISCReportServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MISCReportServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MISCReportServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MISCReportServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetMiniGistDocsDumpReport() {
            return base.Channel.GetMiniGistDocsDumpReport();
        }
        
        public System.Threading.Tasks.Task<string> GetMiniGistDocsDumpReportAsync() {
            return base.Channel.GetMiniGistDocsDumpReportAsync();
        }
    }
}
